Layout/EmptyLines:
  AutoCorrect: false

Layout/EmptyLinesAroundMethodBody:
  AutoCorrect: false

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false
